const animeDB = [
  {
    id: 1,
    rank: 1,
    title: "극장판 귀멸의 칼날: 무한성편 (Demon Slayer: Infinity Castle)",
    releaseDate: "2025-08-22",
    poster: "ani_poster/poster_kimetsuinfinitycastle.jpg",
    director: "소토자키 하루오",
    studio: "ufotable",
    cast: ["하나에 나츠키", "키토 아카리", "시모노 히로", "마츠오카 요시츠구", "사쿠라이 타카히로"],
    genre: ["액션", "다크판타지"],
    runtime: 155,
    koreaAdmissions: "약 570만 명",
    rating: 9.3,
    synopsis:
      "귀살대와 오니의 최종결전을 다룬 3부작 극장판 트릴로지의 첫 번째 작품. 개봉 이후 역대 국내 개봉 일본 영화 흥행 1위를 새로 썼으며, 전 세계 흥행 수입 1조 원을 돌파했다.",
  },
  {
    id: 2,
    rank: 2,
    title: "스즈메의 문단속 (Suzume)",
    releaseDate: "2023-03-08",
    poster: "ani_poster/poster_suzume.jpg",
    director: "신카이 마코토",
    studio: "CoMix Wave Films",
    cast: ["하라 나노카", "마츠무라 호쿠토", "후카츠 에리"],
    genre: ["애니메이션", "판타지", "드라마"],
    runtime: 122,
    koreaAdmissions: "약 559만 명",
    rating: 8.8,
    synopsis:
      "각지의 재앙의 문을 닫는 여행을 떠나게 된 소녀 스즈메의 이야기를 그린 신카이 마코토 감독의 작품. 개봉 당시 국내 개봉 일본 영화 사상 최초로 500만 관객을 돌파했다.",
  },
  {
    id: 3,
    rank: 3,
    title: "더 퍼스트 슬램덩크 (The First Slam Dunk)",
    releaseDate: "2023-01-04",
    poster: "ani_poster/poster_thefirstslamdunk.jpg",
    director: "이노우에 다케히코",
    studio: "도에이 애니메이션",
    cast: ["쿠보즈카 슈고로", "카미오 신이치로", "아마사키 코헤이"],
    genre: ["애니메이션", "스포츠", "드라마"],
    runtime: 124,
    koreaAdmissions: "약 474만 명",
    rating: 9.0,
    synopsis:
      "만화 '슬램덩크'의 극장판. 원작자 이노우에 다케히코가 직접 각본과 감독을 맡았으며, 포인트가드 송태섭(미야기 료타)의 시점에서 재구성된 이야기로 국내에서 재개봉을 거듭하며 장기 흥행에 성공했다.",
  },
  {
    id: 4,
    rank: 4,
    title: "너의 이름은. (Your Name.)",
    releaseDate: "2017-01-04",
    poster: "ani_poster/poster_yourname.jpg",
    director: "신카이 마코토",
    studio: "CoMix Wave Films",
    cast: ["카미키 류노스케", "카미시라이시 모네"],
    genre: ["애니메이션", "판타지", "로맨스"],
    runtime: 106,
    koreaAdmissions: "약 380만 명",
    rating: 8.9,
    synopsis:
      "몸이 뒤바뀌는 소년과 소녀의 운명적인 이야기를 그린 신카이 마코토 감독의 대표작. 오랫동안 국내 최고 흥행 일본 애니메이션 자리를 지켰으며, 재개봉 단골 작품으로 꾸준히 사랑받고 있다.",
  },
  {
    id: 5,
    rank: 5,
    title: "극장판 체인소 맨: 레제편 (Chainsaw Man: The Movie - Reze Arc)",
    releaseDate: "2025-09-24",
    poster: "ani_poster/poster_chainsawmanreze.jpg",
    director: "요시하라 타츠야",
    studio: "MAPPA",
    cast: ["토야 키쿠노스케", "우에다 레이나", "하야미 사오리", "파이루즈 아이"],
    genre: ["액션", "다크판타지", "로맨스"],
    runtime: 100,
    koreaAdmissions: "약 100만 명 이상",
    rating: 8.6,
    synopsis:
      "데블 헌터 덴지가 정체불명의 소녀 레제를 만나며 벌어지는 청춘 로맨스와 고어 액션. 추석 연휴 기간 흥행 돌풍을 일으키며 영화관 특전 품귀 현상을 낳았다.",
  },
  {
    id: 6,
    rank: 6,
    title: "하울의 움직이는 성 (Howl's Moving Castle)",
    releaseDate: "2004-12-24",
    poster: "ani_poster/poster_howlsmovingcastle.jpg",
    director: "미야자키 하야오",
    studio: "스튜디오 지브리",
    cast: ["키무라 타쿠야", "바이쇼 치에코"],
    genre: ["애니메이션", "판타지", "로맨스"],
    runtime: 119,
    koreaAdmissions: "약 300만 명대",
    rating: 9.1,
    synopsis:
      "마녀의 저주로 할머니가 된 소녀 소피가 움직이는 성의 주인 마법사 하울과 만나며 벌어지는 이야기. 국내 개봉 지브리 작품 중 최고 흥행작으로, '너의 이름은.' 등장 전까지 오랫동안 일본 애니메이션 흥행 1위를 지켰다.",
  },
  {
    id: 7,
    rank: 7,
    title: "그대들은 어떻게 살 것인가 (The Boy and the Heron)",
    releaseDate: "2023-08-23",
    poster: "ani_poster/poster_theboyandtheheron.jpg",
    director: "미야자키 하야오",
    studio: "스튜디오 지브리",
    cast: ["산토키 소마", "키무라 타쿠야", "요시다 유리"],
    genre: ["애니메이션", "판타지", "드라마"],
    runtime: 124,
    koreaAdmissions: "약 200만 명대",
    rating: 8.0,
    synopsis:
      "미야자키 하야오 감독의 은퇴 번복작이자 아카데미 장편 애니메이션상 수상작. 어머니를 잃은 소년 마히토가 왜가리를 따라 신비로운 세계로 들어가며 벌어지는 이야기를 그렸다.",
  },
  {
    id: 8,
    rank: 8,
    title: "센과 치히로의 행방불명 (Spirited Away)",
    releaseDate: "2002-06-28",
    poster: "ani_poster/poster_spiritedaway.jpg",
    director: "미야자키 하야오",
    studio: "스튜디오 지브리",
    cast: ["히이라기 루미", "이리노 미유"],
    genre: ["애니메이션", "판타지", "모험"],
    runtime: 125,
    koreaAdmissions: "약 200만 명대",
    rating: 9.4,
    synopsis:
      "신들의 세계로 흘러들어간 소녀 치히로의 성장 모험담을 그린 지브리의 대표작. 국내에 개봉한 일본 영화 최초로 관객 200만 명을 돌파하며 지브리 작품의 국내 흥행 시대를 열었다.",
  },
  {
    id: 9,
    rank: 9,
    title: "벼랑 위의 포뇨 (Ponyo)",
    releaseDate: "2008-12-17",
    poster: "ani_poster/poster_ponyo.jpg",
    director: "미야자키 하야오",
    studio: "스튜디오 지브리",
    cast: ["나라 유리아", "도이 히로키"],
    genre: ["애니메이션", "가족", "판타지"],
    runtime: 100,
    koreaAdmissions: "약 60만 명대",
    rating: 8.3,
    synopsis:
      "인간이 되고 싶은 물고기 소녀 포뇨와 소년 소스케의 우정을 그린 동화 같은 작품. 지브리 특유의 따뜻한 그림체와 음악으로 온 가족이 즐길 수 있는 흥행작.",
  },
  {
    id: 10,
    rank: 10,
    title: "마루 밑 아리에티 (The Secret World of Arrietty)",
    releaseDate: "2010-09-09",
    poster: "ani_poster/poster_arrietty.jpg",
    director: "요네바야시 히로마사",
    studio: "스튜디오 지브리",
    cast: ["시다 미라이", "카미키 류노스케"],
    genre: ["애니메이션", "판타지", "드라마"],
    runtime: 94,
    koreaAdmissions: "약 60만 명대",
    rating: 8.2,
    synopsis:
      "마루 밑에 사는 소인족 소녀 아리에티와 병약한 소년 쇼의 짧고 애틋한 만남을 그린 작품. 극 중후반부로 갈수록 평가가 갈리지만 초반부 감성만큼은 지브리 전성기 작품에 견줄 만하다는 평을 받는다.",
  },
];
